version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - |
        cat << EOF > Dockerrun.aws.json
        {
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "${REPOSITORY_URI}:${IMAGE_TAG}",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": "3000"
            }
          ],
          "Volumes": [
            {
              "HostDirectory": "/var/app/current/logs",
              "ContainerDirectory": "/usr/src/app/logs"
            }
          ],
          "Logging": "/var/log/containers/app.log"
        }
        EOF
      - cat Dockerrun.aws.json

artifacts:
  files:
    - Dockerrun.aws.json
    - .ebextensions/**/*
